name: Auto-updater
on:
  push:
    branches:
    - main
permissions:
  contents: write
jobs:
  check:
    name: Check Changes in Elm Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch gh-pages branch
      run: git fetch origin gh-pages
    - name: Compare with gh-pages branch
      id: check
      run: |
        if [ $(git diff --name-only origin/gh-pages -- src | wc -l) -ne 0 ]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
        else
            echo "result=failed" >> "$GITHUB_OUTPUT"
        fi
    outputs:
      status: ${{ steps.check.outputs.result }}
  compile:
    name: Compile Elm Code
    needs: check
    if: needs.check.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch gh-pages branch
      run: git fetch origin gh-pages
    - name: Merge to gh-pages branch
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'not-a-real-email@fake.com'
        git merge -X ours -m "Merge commit '$(git rev-parse HEAD)' into gh-pages" --allow-unrelated-histories origin/gh-pages
    # Add the elm binary following https://github.com/elm/compiler/blob/master/installers/linux/README.md
    - name: Make bin directory
      run: mkdir -p elm-bin
    - name: Download elm
      uses: sozo-design/curl@v1.0.2
      with:
        args: -L -o elm-bin/elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
    - name: Install elm
      run: |
        cd elm-bin
        gunzip elm.gz
        chmod +x elm
    - name: Compile
      run: |
        ./elm-bin/elm make src/Main.elm --output=www/js/elm.js --optimize &> $GITHUB_STEP_SUMMARY && rm $GITHUB_STEP_SUMMARY
    - name: Push to branch
      run: |
        git add -f www/js/elm.js
        git commit --amend --no-edit
        git push origin HEAD:gh-pages
